-- Food O Friend — seed the 24 /idea screens. Idempotent: re-running updates rows by screen_key.
-- Generated from the same copy as constants/app_idea_content.ts (local fallback).
-- image_url values come from idea_uploaded_urls.json (public URLs in the `idea-assets` bucket).
-- Run AFTER supabase/idea_screens.sql, in the Supabase SQL Editor.

insert into public.idea_screens (
  screen_number, screen_key, journey_key, journey_title, title,
  description, image_path, image_url, image_alt, actions, note, is_active
)
values
  (1, 'welcome', 'account_onboarding', 'Account & Onboarding', 'Welcome',
   'FoodFriend brings people together through shared meals. Discover nearby restaurants, meet people with similar interests, and turn a meal into a new connection.',
   'auth_onboarding/get_started.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/auth_onboarding/get_started.png',
   'Food O Friend welcome screen inviting new users to get started or sign in.',
   '["Get Started — Begin onboarding.", "Sign In — Access an existing account."]'::jsonb,
   null, true),
  (2, 'expand_your_circle', 'account_onboarding', 'Account & Onboarding', 'Expand Your Circle',
   'Step outside your usual circle and meet people who share your taste in food. Join a group meal and start a conversation in a welcoming restaurant.',
   'auth_onboarding/onbording1_auth.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/auth_onboarding/onbording1_auth.png',
   'Onboarding screen about meeting new people who share your taste in food.',
   '[]'::jsonb,
   null, true),
  (3, 'privacy_control', 'account_onboarding', 'Account & Onboarding', 'Privacy & Control',
   'Choose what you share. Your contact details and live location are shared with other members only when you allow it. Meetup suggestions consider your interests and age preferences.',
   'auth_onboarding/onbording2_auth.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/auth_onboarding/onbording2_auth.png',
   'Onboarding screen explaining privacy choices for contact details and live location.',
   '["Review the privacy policy.", "Continue without sharing your live location."]'::jsonb,
   null, true),
  (4, 'build_new_connections', 'account_onboarding', 'Account & Onboarding', 'Build New Connections',
   'Meet nearby people, exchange ideas, and discover different perspectives. Keep the conversation going after dinner to build friendships beyond the table.',
   'auth_onboarding/onbording3_auth.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/auth_onboarding/onbording3_auth.png',
   'Onboarding screen about building friendships that continue after dinner.',
   '[]'::jsonb,
   null, true),
  (5, 'choose_location', 'account_onboarding', 'Account & Onboarding', 'Choose Your Location',
   'Set your location to discover nearby restaurants and group meals.',
   'auth_onboarding/onbording4_auth.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/auth_onboarding/onbording4_auth.png',
   'Location setup screen with options to use your location or choose a city manually.',
   '["Use My Location — Allow location access.", "Choose City Manually — Explore without granting location access.", "Change your selected city later."]'::jsonb,
   null, true),
  (6, 'create_account', 'account_onboarding', 'Account & Onboarding', 'Create Your Account',
   'Create an account with your name, email address, and password. Your account lets you reserve seats, join group conversations, and manage your meetups.',
   'auth_onboarding/create_account.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/auth_onboarding/create_account.png',
   'Account creation form asking for name, email address and password.',
   '["Create a new account.", "Switch to Sign In if you already have one."]'::jsonb,
   null, true),
  (7, 'discover_nearby_meals', 'discover_profile', 'Discover & Manage', 'Discover Nearby Meals',
   'Explore restaurants and available group meals near you. See offers, new arrivals, meal prices, times, and remaining seats.',
   'profile_home/Home_page.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/profile_home/Home_page.png',
   'Home screen listing nearby restaurants and group meals with prices, times and seats left.',
   '["Search or filter available meals.", "Open a restaurant or meetup.", "Save a place to your favourites."]'::jsonb,
   null, true),
  (8, 'restaurant_meetup_details', 'discover_profile', 'Discover & Manage', 'Restaurant & Meetup Details',
   'Review the restaurant, food photos, location, and group meal details before joining. Check the price per person, meetup time, and available seats.',
   'profile_home/detail page.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/profile_home/detail%20page.png',
   'Restaurant detail screen with food photos, location and group meal details.',
   '["Join an available group meal.", "Save the restaurant.", "Continue to reservation confirmation."]'::jsonb,
   null, true),
  (9, 'confirm_your_seat', 'meetup', 'The Meetup Journey', 'Confirm Your Seat',
   'Review your selected meetup, total amount, and payment method. Read the cancellation terms before confirming your reservation.',
   'meetup/1 confirmation.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/meetup/1%20confirmation.png',
   'Reservation confirmation screen summarising the meetup, total amount and payment method.',
   '["Check the restaurant, date, time, and price.", "Open the cancellation policy.", "Confirm and pay to reserve your seat."]'::jsonb,
   null, true),
  (10, 'cancellation_policy', 'meetup', 'The Meetup Journey', 'Cancellation Policy',
   'Understand the cancellation and refund rules before committing. This page explains how cancellation depends on whether the group is still forming or already confirmed.',
   'meetup/2cancellation policy.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/meetup/2cancellation%20policy.png',
   'Cancellation policy screen explaining refund rules for forming and confirmed groups.',
   '["Review cancellation deadlines and refund eligibility.", "Return to your reservation."]'::jsonb,
   'The final policy must define the exact deadlines and any exceptions.', true),
  (11, 'seat_reserved', 'meetup', 'The Meetup Journey', 'Seat Reserved',
   'Your reservation is successful. See your booking details and the current group status.',
   'meetup/3seat reserved.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/meetup/3seat%20reserved.png',
   'Booking success screen showing the reserved seat and current group status.',
   '["Check your reserved seat and payment status.", "Open the group waiting room."]'::jsonb,
   null, true),
  (12, 'group_awaiting_members', 'meetup', 'The Meetup Journey', 'Group Awaiting Members',
   'Your seat is reserved while the group waits for more members. See who has joined, how many seats remain, and the confirmation deadline.',
   'meetup/4group_info awaiting.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/meetup/4group_info%20awaiting.png',
   'Group waiting room showing joined members, remaining seats and the confirmation deadline.',
   '["View member profiles.", "Open the group conversation.", "Track progress toward a confirmed meetup."]'::jsonb,
   null, true),
  (13, 'group_confirmed', 'meetup', 'The Meetup Journey', 'Group Confirmed',
   'The group is full and the meetup is confirmed. Review the final members, restaurant, meal time, and meeting instructions.',
   'meetup/5group_info full.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/meetup/5group_info%20full.png',
   'Confirmed group screen listing the final members, restaurant and meal time.',
   '["Open group chat to coordinate.", "Use voice or video calling.", "Check the meeting point and directions."]'::jsonb,
   null, true),
  (14, 'meeting_point', 'meetup', 'The Meetup Journey', 'Meeting Point',
   'View the agreed meeting location on the map. The group can meet at the restaurant entrance or agree on another pickup point.',
   'meetup/6map_locaition decided.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/meetup/6map_locaition%20decided.png',
   'Map screen showing the group''s agreed meeting point.',
   '["Check the meeting time and location.", "Open directions.", "Share the meeting point in group chat."]'::jsonb,
   null, true),
  (15, 'pickup_points_member_locations', 'meetup', 'The Meetup Journey', 'Pickup Points & Member Locations',
   'Coordinate an optional shared ride using pickup points and member locations. Only members who allow location sharing appear with a live position.',
   'meetup/7map_pickup points.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/meetup/7map_pickup%20points.png',
   'Map screen with shared pickup points and the live positions of members who share their location.',
   '["View shared pickup points.", "Request location access from a member whose position is unknown.", "Continue coordinating if they decline the request."]'::jsonb,
   null, true),
  (16, 'arrival_waiting', 'meetup', 'The Meetup Journey', 'Arrival & Waiting',
   'Let the group know when you arrive at the restaurant. See who has arrived, who is on the way, and who has not checked in.',
   'meetup/8arrival_page.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/meetup/8arrival_page.png',
   'Arrival screen showing which members have arrived, are on the way or haven''t checked in.',
   '["Tap I''ve Arrived.", "Contact the group through chat or calling.", "Wait for the remaining members before dining."]'::jsonb,
   null, true),
  (17, 'start_billing', 'meetup', 'The Meetup Journey', 'Start Billing',
   'After the meal, begin reviewing the bill and each member''s share. Identify the person who paid the restaurant and attach the restaurant bill.',
   'meetup/9start_billing.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/meetup/9start_billing.png',
   'Billing screen showing the bill total, each member''s share and who paid the restaurant.',
   '["Review the bill total and individual amounts.", "Confirm the bill payer, such as Alice.", "Continue to member confirmation."]'::jsonb,
   null, true),
  (18, 'billing_confirmation', 'meetup', 'The Meetup Journey', 'Billing Confirmation',
   'Each member reviews their share and confirms that the amount is correct. The screen shows who has confirmed and who is still pending.',
   'meetup/10billing_confirmation.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/meetup/10billing_confirmation.png',
   'Billing confirmation screen tracking which members have confirmed their share.',
   '["Confirm your amount.", "Raise a billing issue before settlement.", "Track the group''s confirmation progress."]'::jsonb,
   'The proposed 80% confirmation threshold still needs to be finalised.', true),
  (19, 'dinner_wrap_up', 'meetup', 'The Meetup Journey', 'Dinner Wrap-Up',
   'Review the completed meetup and final payment summary. See your share, the bill payer, and the settlement status.',
   'meetup/11dinner wrap up.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/meetup/11dinner%20wrap%20up.png',
   'Dinner wrap-up screen with the final payment summary and settlement status.',
   '["Check the final amount.", "Continue to the transfer result and receipts.", "Keep in touch through group chat."]'::jsonb,
   null, true),
  (20, 'transfer_complete', 'meetup', 'The Meetup Journey', 'Transfer Complete',
   'Your share has been transferred from your FoodFriend wallet to the member who paid the restaurant. For example, Jack''s $24 is transferred to Alice''s wallet because Alice paid the bill.',
   'meetup/12transfer complete.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/meetup/12transfer%20complete.png',
   'Transfer complete screen confirming a wallet transfer to the member who paid the bill.',
   '["Download the wallet transfer receipt.", "Download the restaurant bill paid by Alice.", "Return to your meetup history."]'::jsonb,
   null, true),
  (21, 'upcoming_meetups', 'discover_profile', 'Discover & Manage', 'Upcoming Meetups',
   'Track future reservations and their current status.',
   'profile_home/meetups_incoming.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/profile_home/meetups_incoming.png',
   'Upcoming meetups screen listing future reservations with their status.',
   '["Awaiting your confirmation.", "Waiting for more members.", "Confirmed and ready to attend.", "Cancelled or expired, with the refund status shown."]'::jsonb,
   null, true),
  (22, 'past_meetups', 'discover_profile', 'Discover & Manage', 'Past Meetups',
   'Review previous meals with the restaurant, date, members, and your amount paid.',
   'profile_home/your meetups past.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/profile_home/your%20meetups%20past.png',
   'Past meetups screen listing previous meals with restaurant, date, members and amount paid.',
   '["Return to the group chat.", "View payment details and receipts.", "Save the restaurant to your favourites."]'::jsonb,
   null, true),
  (23, 'notifications', 'discover_profile', 'Discover & Manage', 'Notifications',
   'Stay updated on nearby meetups and changes to your groups. Notifications can highlight someone from a previous meal, an available seat, a member leaving, or a refund.',
   'profile_home/notifications.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/profile_home/notifications.png',
   'Notifications screen with updates about nearby meetups, open seats, members leaving and refunds.',
   '["Open the related meetup or profile.", "Respond to updates that need your attention."]'::jsonb,
   null, true),
  (24, 'member_profile', 'discover_profile', 'Discover & Manage', 'Member Profile',
   'Get to know another member before or after a meetup. View their photo, name, age, work, interests, and favourite sports.',
   'profile_home/profile.png',
   'https://nipbfuwpxuoibuornhfd.supabase.co/storage/v1/object/public/idea-assets/profile_home/profile.png',
   'Another member''s profile showing their photo, age, work, interests and favourite sports.',
   '["Discover shared interests.", "View shared meetup history where available.", "Connect through the group conversation."]'::jsonb,
   null, true)
on conflict (screen_key)
do update set
  journey_key = excluded.journey_key,
  journey_title = excluded.journey_title,
  screen_number = excluded.screen_number,
  title = excluded.title,
  description = excluded.description,
  image_path = excluded.image_path,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  actions = excluded.actions,
  note = excluded.note,
  is_active = excluded.is_active,
  updated_at = now();
