import type { Metadata } from "next";
import { AppStrings } from "@/constants/app_strings";

const { brand, metadata: defaults } = AppStrings;

export const OPEN_GRAPH_DEFAULTS = {
  type: "website",
  siteName: brand.name,
  locale: "en_US",
} as const;

/** Generated by app/opengraph-image.tsx; repeated here because page-level openGraph replaces the inherited one. */
const SHARED_SOCIAL_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: defaults.ogImageAlt,
};

interface PageMetadataInput {
  title: string;
  description: string;
  path: string;
}

/**
 * Per-page metadata with canonical URL and matching Open Graph/Twitter fields.
 * (Nested `openGraph` objects replace the layout's, so shared fields are repeated here.)
 */
export const buildPageMetadata = ({ title, description, path }: PageMetadataInput): Metadata => {
  const socialTitle = `${title} | ${brand.name}`;
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: { ...OPEN_GRAPH_DEFAULTS, title: socialTitle, description, url: path, images: [SHARED_SOCIAL_IMAGE] },
    twitter: { card: "summary_large_image", title: socialTitle, description, images: [SHARED_SOCIAL_IMAGE] },
  };
};

export const rootMetadataDefaults = { title: defaults.title, description: defaults.description };
